# Generated by Django 6.0.6 on 2026-07-11 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_brand_categorymodels_parent_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categorymodels",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
